from collinearity_tool import collinearity_tool
import altair as alt
import numpy as np
import pandas as pd

def test_corr_heatmap():
    """Test corr_heatmap function
    
    Parameters
    ----------
    heatmap : altair.LayerChart 
        The heatmap generated by corr_heatmap function
    
    Examples
    --------
    >>> test_corr_heatmap(heatmap)
    """

    assert isinstance(heatmap, alt.LayerChart)
    assert len(heatmap.layer) == 2, 'the heatmap does not have base and label on it'
    assert heatmap.layer[0].mark == 'rect', 'mark of base should be a rectangle'
    assert heatmap.layer[0].encoding.x.field == 'variable1', 'x_axis should be mapped to the variable1'
    assert heatmap.layer[0].encoding.y.field == 'variable2', 'y_axis should be mapped to the variable2'
    assert heatmap.layer[0].encoding.color.field == 'correlation', 'y_axis should be mapped to the correlation'
    assert heatmap.layer[0].encoding.color.scale.domain == [-1, 1], "correlation should has domain to be [-1, 1]"
    assert heatmap.layer[0].encoding.x.type == 'ordinal', "x-axis should be ordinal"
    assert heatmap.layer[0].encoding.y.type == 'ordinal', "y-axis should be ordinal"
    assert heatmap.layer[0].encoding.color.type == 'quantitative', "color should be quantitative"
    assert heatmap.layer[1].mark == 'text', 'mark of label should be a text'
    assert heatmap.layer[1].encoding.text.field == 'rounded_corr', 'text should be mapped to the rounded correlation'
    assert heatmap.layer[1].encoding.text.type == 'nominal', 'text should be nominal'
